"""Semantic scalar types used at domain, protocol, and scheduling boundaries."""

from typing import NewType

Seconds = NewType("Seconds", float)
"""A duration measured in seconds."""

GameSeed = NewType("GameSeed", int)
CaseId = NewType("CaseId", str)
SuiteId = NewType("SuiteId", str)
PolicyId = NewType("PolicyId", str)
ActionIndex = NewType("ActionIndex", int)
Keycode = NewType("Keycode", int)
StepLimit = NewType("StepLimit", int)
WorkerCount = NewType("WorkerCount", int)
WorkerIndex = NewType("WorkerIndex", int)
EpisodeIndex = NewType("EpisodeIndex", int)
StartupAttemptCount = NewType("StartupAttemptCount", int)
StartupAttemptIndex = NewType("StartupAttemptIndex", int)
CaseCount = NewType("CaseCount", int)
CaseIndex = NewType("CaseIndex", int)
FrameLimit = NewType("FrameLimit", int)
ViewRadius = NewType("ViewRadius", int)
GridColumnCount = NewType("GridColumnCount", int)
DcssVersion = NewType("DcssVersion", str)
VisibleCellCount = NewType("VisibleCellCount", int)
EpochCount = NewType("EpochCount", int)
BatchSize = NewType("BatchSize", int)
InferenceBatchSize = NewType("InferenceBatchSize", int)
InferenceBatchCount = NewType("InferenceBatchCount", int)
MeanInferenceBatchSize = NewType("MeanInferenceBatchSize", float)
FeatureCount = NewType("FeatureCount", int)
FeatureSpecVersion = NewType("FeatureSpecVersion", int)
AffordanceEventCount = NewType("AffordanceEventCount", int)
TrajectoryCount = NewType("TrajectoryCount", int)
ImitationSampleCount = NewType("ImitationSampleCount", int)
ImitationReplayCacheKey = NewType("ImitationReplayCacheKey", str)
CrawlLogCount = NewType("CrawlLogCount", int)
ActionCount = NewType("ActionCount", int)
LearningRate = NewType("LearningRate", float)
LossWeight = NewType("LossWeight", float)
Probability = NewType("Probability", float)
RewardWeight = NewType("RewardWeight", float)
DecisionCost = NewType("DecisionCost", float)
ShortCycleCost = NewType("ShortCycleCost", float)
DecisionWindow = NewType("DecisionWindow", int)
CycleStateDigest = NewType("CycleStateDigest", str)
TerminalOutcome = NewType("TerminalOutcome", str)
CheckpointId = NewType("CheckpointId", str)
DecisionsPerSecond = NewType("DecisionsPerSecond", float)
DecisionProgressArea = NewType("DecisionProgressArea", int)
DepthWeightedDiscovery = NewType("DepthWeightedDiscovery", int)
LevelCount = NewType("LevelCount", int)
PlaceId = NewType("PlaceId", str)
type LevelId = tuple[PlaceId, int]
UpdateCount = NewType("UpdateCount", int)
RolloutLength = NewType("RolloutLength", int)
ActionHistoryLength = NewType("ActionHistoryLength", int)
UnixSocketPathBytes = NewType("UnixSocketPathBytes", int)

type Coordinate = tuple[int, int]
